# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_cambio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_cambio',
            name='fecha',
            field=models.DateField(verbose_name='fecha de cambio'),
        ),
    ]
